# Generated by Django 4.0.4 on 2022-09-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='module_duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
