# Generated by Django 4.0.4 on 2022-09-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
