# Generated by Django 4.0.4 on 2023-03-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
