# Generated by Django 4.0.4 on 2022-08-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_picture_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
