# Generated by Django 4.0.4 on 2022-08-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rating_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
