# Generated by Django 4.0.4 on 2022-09-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
